import math

#################
# KEYS
#################
BUTTON1 = "<Button-1>"
BUTTON1_MOVE = "<B1-Motion>"
BUTTON2 = "<Button-2>"
STOP_KEY = 's'


#################
# settings
#################
BUTTON_HEIGHT = 200
BUTTON_WIDHT = 200
CANVAS_WIDTH = 1300
CANVAS_HEIGHT = 800 - BUTTON_HEIGHT
BOX_SHIFT = 100
DEFAULT_NUM_OF_POINTS = 10000
DEFAULT_NUM_OF_CURVE_POINTS = 10
DEFAULT_NUM_OF_POINTS_SMALL = 500
SLEEP_PERIOD = 0.1
TURNING_PERIOD = 100
TURN_ANGLE = math.pi / 20
POINT_RADIUS = 40
